In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [4]:
#Creating a Numpy Araay

lst = [1,2,3,4]

arr=np.array(lst)
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
#.dtype attribute



a=np.array([1.1,2.2,3.3])
print(a.dtype)

float64


In [13]:
"""
Size Comparison of ndarray and list objects
"""

from sys import getsizeof

lst=[1,2,3,5,6,7,8,9,10,11,22]
print(getsizeof(lst))

arr=np.array([1,2,3,6,5,7,8,9,10,11,22])
print(getsizeof(arr))

144
148


In [19]:
"""
Operations with Numpy Arrays
"""

prices=[30,25,40,20,20]
price_arr=np.array(prices)

new_prices=[price-5 for price in prices]
print(new_prices)

#with a ndarray
price_arr -= 5
print(price_arr)





[25, 20, 35, 15, 15]
[25 20 35 15 15]


In [34]:
test_1=np.array([92,94,88,91,87])
test_2=np.array([79,100,86,93,91])
test_3=np.array([87,85,72,90,92])

test_3_fixed= test_3+2
print(test_3_fixed)

total_grade=test_1+test_2+test_3_fixed
print(total_grade)

final_grade=total_grade/3
print(final_grade)

student_scores=np.array([test_1,test_2,test_3_fixed])
print(student_scores)

jeremy_test_2=student_scores[1,3]
print(jeremy_test_2)

manual_adwoa_test_1=np.array([student_scores[0,1], student_scores[0,2]])
print(manual_adwoa_test_1)

print(student_scores[:,-1])

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]
93
[94 88]
[87 91 94]


In [40]:
"""
Logical Operations with Arrays
"""

#masking
a=np.array([10,2,2,4,5,3,9,8,8])
mask=a>5
print(mask)

#select using Logical opreations
selected = a[a>5]
print(selected)

#combined Logical opreations

selected=a[(a>5) | (a<4)]
print(selected)

selected=a[(a>3) & (a<8)]
print(selected)

[ True False False False False False  True  True  True]
[10  9  8  8]
[10  2  2  3  9  8  8]
[4 5]


In [41]:
porridge=np.array([79,65,50,63,56,90,85,98,79,51])

cold=porridge