In [2]:
import numpy as np

In [3]:
"""
Numpy Array Attributes
"""

print(np.arange(3))
print(np.arange(3,9))
print(np.arange(3,9,2))

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [30]:
np.random.seed(0)
arr1=np.random.randint(10,size=(3,4,5))
print(arr1)


[[[5 0 3 3 7]
  [9 3 5 2 4]
  [7 6 8 8 1]
  [6 7 7 8 1]]

 [[5 9 8 9 4]
  [3 0 3 5 0]
  [2 3 8 1 3]
  [3 3 7 0 1]]

 [[9 9 0 4 7]
  [3 2 7 2 0]
  [0 4 5 5 6]
  [8 4 1 4 9]]]


In [38]:
np.random.seed(1)
arr = np.random.randint(10,size=(3,4))
print(arr)

print("arr.ndim=", arr.ndim)
print("arr.shape=", arr.shape)
print("arr.size=", arr.size)
print("arr.dtype=", arr.dtype)
print("arr.itemsize=", arr.itemsize)
print("arr.nbytes=", arr.nbytes)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
arr.ndim= 2
arr.shape= (3, 4)
arr.size= 12
arr.dtype= int32
arr.itemsize= 4
arr.nbytes= 48


In [42]:
"""
slicing
"""

arr=np.arange(10)
print(arr)

print(arr[3:7])
print(arr[:7])
print(arr[3:])
print(arr[3:7:2])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4 5 6]
[3 4 5 6 7 8 9]
[3 5]


In [45]:
np.random.seed(2)
arr = np.random.randint(10,size=(6,8))
print(arr)

arr_sub=arr[:2,:2]
print(arr_sub)

arr_sub[0,0]=99
print(arr)

[[8 8 6 2 8 7 2 1]
 [5 4 4 5 7 3 6 4]
 [3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4]
 [1 7 8 2 9 8 7 1]
 [6 8 5 9 9 9 3 0]]
[[8 8]
 [5 4]]
[[99  8  6  2  8  7  2  1]
 [ 5  4  4  5  7  3  6  4]
 [ 3  7  6  1  3  5  8  4]
 [ 6  3  9  2  0  4  2  4]
 [ 1  7  8  2  9  8  7  1]
 [ 6  8  5  9  9  9  3  0]]


In [50]:
"""
Subarrays as no-copy views
"""

np.random.seed(2)
arr = np.random.randint(10,size=(6,8))
print(arr)

arr_sub=arr[:2,:2].copy()
print(arr_sub)

arr_sub[0,0]=99
print(arr_sub)

print(arr)

[[8 8 6 2 8 7 2 1]
 [5 4 4 5 7 3 6 4]
 [3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4]
 [1 7 8 2 9 8 7 1]
 [6 8 5 9 9 9 3 0]]
[[8 8]
 [5 4]]
[[99  8]
 [ 5  4]]
[[8 8 6 2 8 7 2 1]
 [5 4 4 5 7 3 6 4]
 [3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4]
 [1 7 8 2 9 8 7 1]
 [6 8 5 9 9 9 3 0]]


In [54]:
"""
Reshaping of Arrays
"""

arr=np.arange(1,10)
print(arr,'\n')

grid=arr.reshape(3,3)
print(grid,'\n')

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [58]:
"""
Array Concatenation
"""
arr_1=np.array([1,2,3])
arr_2=np.array([4,5,6])
arr_3=np.array([7,8,9])

arr_sum=np.concatenate([arr_1,arr_2,arr_3])
print(arr_sum)

arr_total=np.vstack([arr_1,arr_2,arr_3])
print(arr_total)

arr_total=np.hstack([arr_1,arr_2,arr_3])
print(arr_total)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [65]:
"""
Array Splitting
"""

arr=[1,2,3,99,99,3,2,1]
print(arr,'\n')

arr_1, arr_2,arr_3=np.split(arr, [3,5])
print(arr_1,arr_2,arr_3)

[1, 2, 3, 99, 99, 3, 2, 1] 

[1 2 3] [99 99] [3 2 1]
