In [1]:
import numpy as np

In [4]:
"""
Comparison:Loop vs ufuncs
"""

big_array=np.random.randint(1,100,size=1000000)

%timeit big_array



21.3 ns ± 0.146 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [5]:

%timeit 1 / big_array

2.44 ms ± 41.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
"""
numpy.ufunc
"""

np.random.seed(1)
arr1=np.random.randint(10,size=(5))
arr2=np.random.randint(10,size=(5))
print(arr1,arr2)

arr1=arr2-2
print(arr1)

arr3=arr1+arr2
print(arr3)

arr4=np.random.randint(10,size=(3,5))
print(arr4)

arr5=arr4**2
print(arr5)

[5 8 9 5 0] [0 1 7 6 9]
[-2 -1  5  4  7]
[-2  0 12 10 16]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [14]:
x=np.arange(4)
print(x+5)
np.add(x,5)

[5 6 7 8]


array([5, 6, 7, 8])

In [17]:
"""
UFuncs:Absolute Value
"""

x=np.array([-2,-1,0,1,2])
print(np.abs(x))

x=np.array([3-4j,4-4j,2+0j,0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5.         5.65685425 2.         1.        ]


In [20]:
"""
UFuncs:Trigonometric Functions
"""

theta=np.linspace(0,np.pi,3)
print(theta)

print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [23]:
"""
UFuncs:Aggregation
"""

x=np.arange(1,5)
print(x)

aggr=np.add.reduce(x)
print(aggr)

aggr=np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [26]:
#accumulate()

x=np.arange(1,15)
print(x)

accum=np.add.accumulate(x)
print(accum)

accum=np.multiply.accumulate(x)
print(accum)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105]
[         1          2          6         24        120        720
       5040      40320     362880    3628800   39916800  479001600
 1932053504 1278945280]


In [29]:
np.random.seed(2)
arr=np.random.rand(1000000)
print(arr)

print('sum=', np.sum(arr))

%timeit sum(arr)

[0.4359949  0.02592623 0.54966248 ... 0.78483191 0.00778062 0.42442656]
sum= 499468.5166853333
79.7 ms ± 685 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [31]:
%timeit np.sum(arr)

288 µs ± 1.12 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [36]:

np.random.seed(5)

arr=np.random.randint(10,size=(3,4))
print(arr)

print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[12 14 17  8]
[15 28  8]
